### ISSUE TITLE
No module named 'ipympl'

### ISSUE THREAD

**Issue by XerMat** [charwick/helipad#2]
I have installed helipad via pip on a Ubuntu system that has Anaconda installed.  I cannot run any of the the samples.  The same error is returned:
```
runfile('/home/zinvor/HelipadSpace/helipad-master/sample-models/Cities.py', wdir='/home/zinvor/HelipadSpace/helipad-master/sample-models')
Traceback (most recent call last):

  File "/home/zinvor/HelipadSpace/helipad-master/sample-models/Cities.py", line 186, in <module>
    viz = heli.useVisual(TimeSeries)

  File "/home/zinvor/.local/lib/python3.9/site-packages/helipad/model.py", line 356, in useVisual
    self.visual = viz(self) if viz is not None else None

  File "/home/zinvor/.local/lib/python3.9/site-packages/helipad/visualize.py", line 94, in __init__
    super().__init__(model)

  File "/home/zinvor/.local/lib/python3.9/site-packages/helipad/visualize.py", line 55, in __init__
    get_ipython().magic('matplotlib widget')

  File "/usr/lib/python3/dist-packages/IPython/core/interactiveshell.py", line 2434, in magic
    return self.run_line_magic(magic_name, magic_arg_s, _stack_depth=2)

  File "/usr/lib/python3/dist-packages/IPython/core/interactiveshell.py", line 2336, in run_line_magic
    result = fn(*args, **kwargs)

  File "<decorator-gen-101>", line 2, in matplotlib

  File "/usr/lib/python3/dist-packages/IPython/core/magic.py", line 187, in <lambda>
    call = lambda f, *a, **k: f(*a, **k)

  File "/usr/lib/python3/dist-packages/IPython/core/magics/pylab.py", line 99, in matplotlib
    gui, backend = self.shell.enable_matplotlib(args.gui.lower() if isinstance(args.gui, str) else args.gui)

  File "/usr/lib/python3/dist-packages/IPython/core/interactiveshell.py", line 3515, in enable_matplotlib
    pt.activate_matplotlib(backend)

  File "/usr/lib/python3/dist-packages/IPython/core/pylabtools.py", line 322, in activate_matplotlib
    plt.switch_backend(backend)

  File "/usr/lib/python3/dist-packages/matplotlib/pyplot.py", line 276, in switch_backend
    class backend_mod(matplotlib.backend_bases._Backend):

  File "/usr/lib/python3/dist-packages/matplotlib/pyplot.py", line 277, in backend_mod
    locals().update(vars(importlib.import_module(backend_name)))

  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)

  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import

  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load

  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked

  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed

  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import

  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load

  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked

ModuleNotFoundError: No module named 'ipympl'
```

I installed imympl and pwm separately for good measure using pip but continue to see the same.  What is producing this behavior?

**Comment by charwick** [comment]
This one's tricky: the console in Spyder is an Ipython console, so Helipad thinks it's in a Jupyter notebook and tries to initialize the inline Matplotlib widget with Ipympl. Unfortunately a lot of methods of distinguishing the frontend are unreliable since Jupyter tries to prevent user code from figuring that out. I'll experiment with some better ways of doing that.

**Comment by XerMat** [comment]
Ah, that's interesting. What did you use for an IDE?  I'll need to try from
a command prompt.

**Comment by charwick** [comment]
Ok, so I've been able to distinguish between the Jupyter notebook and the Ipython console (https://github.com/charwick/helipad/commit/2445fc7b6ca4a80e4f89a11dce35d36a4410a393 ), but now it looks like Spyder is running its own event loop in a way that prevents Helipad's visualizer from ever updating. Looking around, it looks like Spyder is notorious for being difficult to run `async` code. I'll keep trying to find a way to make it work.

Running from the command line ought to work; that's how I've tested it on MacOS and Windows in the past. If I get it working in Spyder though, I'll test it that way too going forward.

**Comment by charwick** [comment]
Here we go: patching `asyncio` with `nest-asyncio` gets it running in Spyder (https://github.com/charwick/helipad/commit/d98a75034aec51bfe8a5e57a64f54c30da349105 ). `nest-asyncio` is packaged with Anaconda and is only used when running from Spyder, so this shouldn't cause any dependency troubles. I've just pushed 1.3.2 with the fix.

**Comment by XerMat** [comment]
Brilliant. I can confirm that I can now run Helicopter.py from Spider 5.05
on Windows 10 (python  3.8.5, Anaconda3).

Also on Ubuntu 21.04 I ran pip install -U helipad and version 1 3.2 is
shown installed.  Here I am using Spyder 4.2.5 launched from Anaconda
navigator  (version 5 does not appear to be available for Linux) and Python
3.9.5.

I am enjoying working through your paper, the code (decorators are new to
me), and Selgin's book.

**Comment by XerMat** [comment]
Minor correction. That's Python 3.8.10 on Ubuntu.
